# Generated by Django 4.0.2 on 2022-02-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='text',
            new_name='Post',
        ),
    ]
